.gitignore
DEPLOYMENT_GUIDE.md
DEPLOYMENT_README.md
DEPLOYMENT_STATUS.md
MANUAL_DEPLOYMENT_STEPS.md
build-frontend-fix.sh
build-frontend.sh
build-static.sh
client/build-render.js
client/build.sh
client/public/index.html
client/src/components/SubscriptionManagement.js
client/src/components/UserManagement.js
deploy.bat
deploy.sh
frontend/package.json
frontend/public/index.html
h
package-lock.json
package.json
render.yaml
server/models/User.js
server/package-lock.json
server/package.json
server/routes/auth.js
test-deployment.js
